# Generated by Django 5.0.4 on 2024-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayMessage',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='Date posted')),
                ('timestamp_ms', models.IntegerField()),
                ('id', models.CharField(max_length=39, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
