AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Create an API Gateway and a Lambda to call a FastAPI app
Parameters:
  functionName:
    Description: The name of the lambda function
    Type: String
    MinLength: 1
    MaxLength: 100
  VPCsecurityGroupID:
    Description: The ID of the security group in the VPC
    Type: String
    MinLength: 1
    MaxLength: 300
  VPCsubnetIDlist:
    Description: A comma-separated list (in one string) of subnet IDs in the VPC
    Type: String
    MinLength: 1
    MaxLength: 300
  timeout:
    Description: Timeout in seconds for the lambda
    Type: Number
    MinValue: 1
    Default: 10

Resources:

  logGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupClass: STANDARD
      RetentionInDays: 3
      LogGroupName:
        !Join
        - '/'
        - - 'lambda-log'
          - !Ref functionName

  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: functionName
      Architectures:
        - x86_64
      MemorySize: 128
      PackageType: Zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: lambda
      Description: A Lambda to call a FastAPI app
      Timeout: !Ref timeout
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Layers:
        - Ref: libs
      Events:
        TODO
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCsecurityGroupID
        SubnetIds: !Split [",", !Ref VPCsubnetIDlist]
      LoggingConfig:
        LogFormat: Text
        LogGroup: !Ref logGroup

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        !Join
        - '-'
        - - !Ref functionName
          - 'layer'
      Description: Python packages used by the lambda.
      ContentUri: package
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.10
