name: aws-deploy

on:
    workflow_run:
      workflows:
        - tests
      types:
        - completed
env:
    CLOUD_URL: ${{ vars.CLOUD_URL }}
    LOG_LEVEL: ${{ vars.LOG_LEVEL }}
    NAME_PREFIX: ${{ vars.NAME_PREFIX }}
    LAMBDA_TIMEOUT_SEC: ${{ vars.LAMBDA_TIMEOUT_SEC }}

jobs:
  aws-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare test environment
      uses: ./.github/actions/prepare-test-environment
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: deploy to aws and run cloud tests
      run: |
        ./setup.sh
