name: flake8

on: [push, workflow_dispatch]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install flake8
    - name: flake8
      run: python -m flake8 --exclude=tests/*,venv/*,cloud_tests/*,django_app/django_app/settings.py,django_app/app/migrations/*
    - name: Save result
      if: always()
      uses: ./.github/actions/save-workflow-result
      with:
        result: ${{ job.status }}
