name: mypy

on: [push, workflow_dispatch]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install mypy
      - name: mypy
        run: python -m mypy . --explicit-package-bases --exclude 'tests/' --exclude 'venv/' --exclude 'cloud_tests/'
      - name: Save result
        if: always()
        uses: ./.github/actions/save-workflow-result
        with:
          result: ${{ job.status }}
